server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer8803
  rabbitmq:
    host: 10.211.55.7
    port: 5672
    username: admin
    password: 123456
  cloud:
    stream:
      binders: # 在此处配置要绑定的 rabbitmq 的服务信息；
        rabbit: # 表示定义的名称，用于于 binding 整合
          type: rabbit # 消息组件类型
          environment:  # 设置 rabbitmq 的相关的环境配置
            spring:
              rabbitmq:
                host: 10.211.55.7
                port: 5672
                username: admin
                password: 123456
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的 Exchange 名称定义
          content-type: application/json # 设置消息类型，本次为 json ，文本则设置 “text/plain”
          binder: rabbit # 设置要绑定的消息服务的具体设置
          group: rabbitA

eureka:
  client: # 客户端进行 Eureka 注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是 30 秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了 5 秒的间隔（默认是 90 秒）
    instance-id: send-8801.com  # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为 IP 地址