### consul 服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
### consul 注册中心地址
  cloud:
    consul:
#      host: 10.211.55.5
      host: localhost
      port: 8500
      discovery:
        # hostname: 127.0.0.1
        server-name: ${spring.application.name}